[package]
name = "buckshock"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.8"
log = "0.4.29"
logwatcher = "0.1.1"
rzap-ng = "0.2.2"
serde = "1.0.228"
tokio = "1.48.0"
toml = "0.9.8"
