own_name = "sophie"
shocker_id = "some long ass uuid"
openshock_token = "an openshock token"
shock_intensity = 50                   # 0-100 i think
shock_duration = 200                   # ms probably
